CREATE TABLE championship (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(120) NOT NULL,
    season  INTEGER      NOT NULL,
    country VARCHAR(80),
    status  VARCHAR(20)  NOT NULL,

    CONSTRAINT uk_championship_name_season UNIQUE (name, season),
    CONSTRAINT ck_championship_status CHECK (status IN ('UPCOMING', 'ONGOING', 'FINISHED'))
);