CREATE TABLE team (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(80) NOT NULL,
    constructor_name VARCHAR(80) NOT NULL,
    country VARCHAR(80),

    CONSTRAINT uk_team_name UNIQUE (name)
);