CREATE TABLE driver (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(60) NOT NULL,
    surname       VARCHAR(60) NOT NULL,
    nationality   VARCHAR(60) NOT NULL,
    date_of_birth DATE        NOT NULL
);