CREATE TABLE circuit (
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(120)  NOT NULL,
    country   VARCHAR(80)   NOT NULL,
    city      VARCHAR(80),
    length_km NUMERIC(5, 3) NOT NULL,

    CONSTRAINT uk_circuit_name UNIQUE (name),
    CONSTRAINT ck_circuit_length_km CHECK (length_km > 0)
);