CREATE TABLE race (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT       NOT NULL,
    circuit_id      BIGINT       NOT NULL,
    name            VARCHAR(120) NOT NULL,
    round           INTEGER      NOT NULL,
    scheduled_at    TIMESTAMPTZ  NOT NULL,
    status          VARCHAR(20)  NOT NULL,

    CONSTRAINT fk_race_championship FOREIGN KEY (championship_id)
        REFERENCES championship (id) ON DELETE RESTRICT,

    CONSTRAINT fk_race_circuit FOREIGN KEY (circuit_id)
        REFERENCES circuit (id) ON DELETE RESTRICT,

    CONSTRAINT uk_race_championship_round UNIQUE (championship_id, round),
    CONSTRAINT ck_race_round CHECK (round > 0),
    CONSTRAINT ck_race_status CHECK (status IN ('SCHEDULED', 'IN_PROGRESS', 'FINISHED'))
);

CREATE INDEX idx_race_circuit ON race (circuit_id);