CREATE TABLE championship_entry (
    id              BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    championship_id BIGINT  NOT NULL,
    driver_id       BIGINT  NOT NULL,
    team_id         BIGINT  NOT NULL,
    car_number      INTEGER NOT NULL,

    CONSTRAINT fk_entry_championship FOREIGN KEY (championship_id)
        REFERENCES championship (id) ON DELETE RESTRICT,

    CONSTRAINT fk_entry_driver FOREIGN KEY (driver_id)
        REFERENCES driver (id) ON DELETE RESTRICT,

    CONSTRAINT fk_entry_team FOREIGN KEY (team_id)
        REFERENCES team (id) ON DELETE RESTRICT,

    CONSTRAINT uk_entry_championship_driver UNIQUE (championship_id, driver_id),
    CONSTRAINT uk_entry_championship_car_number UNIQUE (championship_id, car_number),
    CONSTRAINT ck_entry_car_number CHECK (car_number BETWEEN 1 AND 99)
);

CREATE INDEX idx_entry_driver ON championship_entry (driver_id);
CREATE INDEX idx_entry_team ON championship_entry (team_id);